spring.datasource.url=jdbc:postgresql://ep-crimson-cherry-an3zd7ka-pooler.c-6.us-east-1.aws.neon.tech/neondb
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name= test
spring.security.user.password= test