spring.application.name=SchoolApp
spring.datasource.url = jdbc:postgresql://dpg-d45h0i15pdvs73c26i00-a.oregon-postgres.render.com:5432/school_database_1lbw
#postgresql://school_database_1lbw_user:2389xC4uyUgjklbdUOBPIrTciw2Ijkmz@dpg-d45h0i15pdvs73c26i00-a.oregon-postgres.render.com/school_database_1lbw
spring.datasource.username =school_database_1lbw_user
spring.datasource.password=2389xC4uyUgjklbdUOBPIrTciw2Ijkmz
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name= test
spring.security.user.password= test
