<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/school_management
spring.datasource.username=postgres
spring.datasource.password=damilare
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name= test
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/school_management
spring.datasource.username=postgres
spring.datasource.password=damilare
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name= test
>>>>>>> 10b1763cfe6c8830f676d55680d0f9367fa3a19f
spring.security.user.password= test